import Head from 'next/head'
import { Navbar } from '../navbar/Navbar'
import styles from './MainLayout.module.css'
import React, { FC, PropsWithChildren } from 'react'

export const MainLayout: FC<PropsWithChildren> = ({children}) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Home - Khail</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
    
            <Navbar />
    
            <main className={styles.main}>
    
                {children}
    
            </main>
        </div>
    )
}
